title: FsArduino
description: Creating a integration between Flight Simulator 2020 and Arduino
author:
  name: "Bart Roozendaal"
  email: "bart@fsarduino.com"
  url: "https://fsarduino.com"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
theme: jekyll-theme-minimal
# Custom variables
owner : "Bart Roozendaal"
year : "2020"
